#!/bin/sh

BASE=$(pwd)

mkdir ~/.bac
### Remove files
mv ~/.bashrc ~/.bac/
mv ~/.bash_profile ~/.bac/
mv ~/.inputrc ~/.bac/
mv ~/.vimrc ~/.bac/
mv ~/.ctags ~/.bac/
mv ~/.gitconfig ~/.bac/
mv ~/.config/nvim/ ~/.bac/

mkdir -p ~/.config/nvim/
mkdir -p ~/.vim/
mkdir -p ~/.sh.d/
mkdir -p ~/.sh.d/os

ln -sf $BASE/bashrc
ln -sf $BASE/bash_profile
ln -sf $BASE/inputrc
ln -sf $BASE/tmux.conf
ln -sf $BASE/gitconfig
ln -sf $BASE/ctags
ln -sf $BASE/vimrc ~/.vimrc
ln -sf $BASE/vimrc ~/.config/nvim/init.vim
ln -sf $BASE/sh.d/prompt.bash ~/.sh.d/prompt.bash
ln -sf $BASE/sh.d/z.sh ~/.sh.d/z.sh
ln -sf $BASE/sh.d/fzf.bash ~/.sh.d/fzf.bash
ln -sf $BASE/sh.d/os/linux.bash ~/.sh.d/linux.bash
ln -sf $BASE/sh.d/os/linux-env.bash ~/.sh.d/linux-env.bash

vim +PlugInstall +qall
