### Config
MPD_HOST=$USER
QT_QPA_PLATFORMTHEME="qt5ct"
XDG_CONFIG_HOME=$HOME/.config
MAIL=/var/mail/$USER
W3MIMGDISPLAY_PATH=$HOME/bin/misc/w3mfix
ABDUCO_CMD="dvtm -m ^o"
UNZIP="-O cp949"
ZIPINFO="-O cp949"
NNN_USE_EDITOR=1
DUCK_THEME=colory
DUCK_COLOR=misty

export  OS VER MPD_HOST QT_QPA_PLATFORMTHEME XDG_CONFIG_HOME MAIL GPGKEY \
        DUCK_THEME DUCK_COLOR UNZIP ZIPINFO ABDUCO_CMD NNN_USE_EDITOR \
